import type { LogbookSection, LogbookFormValues } from "../types/logbook_types";

export const logbook_sections: LogbookSection[] = [
    {
        id: "identity",
        title: "Aircraft and entry",
        fields: [
            {
                key: "aircraft",
                label: "Aircraft registration",
                type: "aircraft",
                required: true,
                hint: "Select an aircraft from the current records.",
            },
            {
                key: "entry_date",
                label: "Entry date (UTC)",
                type: "date",
                required: true,
                hint: "",
            },
            {
                key: "log_page",
                label: "Paper log page",
                type: "text",
                required: false,
                hint: "Optional reference to the source paper page.",
            },
        ],
    },
    {
        id: "flight",
        title: "Flight record",
        fields: [
            {
                key: "station_from",
                label: "Station from",
                type: "text",
                required: false,
                hint: "",
            },
            {
                key: "station_to",
                label: "Station to",
                type: "text",
                required: false,
                hint: "",
            },
            {
                key: "out_time",
                label: "OUT time (UTC)",
                type: "time",
                required: false,
                hint: "",
            },
            {
                key: "off_time",
                label: "OFF time (UTC)",
                type: "time",
                required: false,
                hint: "",
            },
            {
                key: "on_time",
                label: "ON time (UTC)",
                type: "time",
                required: false,
                hint: "",
            },
            {
                key: "in_time",
                label: "IN time (UTC)",
                type: "time",
                required: false,
                hint: "",
            },
            {
                key: "flight_time",
                label: "Flight time (hours)",
                type: "number",
                required: false,
                hint: "Enter the recorded value. No duration calculation is applied.",
            },
            {
                key: "block_time",
                label: "Block time (hours)",
                type: "number",
                required: false,
                hint: "Confirm decimal-hours notation with Shuttle Air.",
            },
            {
                key: "commander_name",
                label: "Commander name",
                type: "text",
                required: false,
                hint: "",
            },
            {
                key: "commander_licence",
                label: "Commander licence number",
                type: "text",
                required: false,
                hint: "",
            },
            {
                key: "commander_utc_date",
                label: "Commander UTC date",
                type: "date",
                required: false,
                hint: "Name and licence details do not constitute a signature.",
            },
        ],
    },
    {
        id: "defects",
        title: "Defects and action",
        fields: [
            {
                key: "defects",
                label: "Defects / Remarks",
                type: "textarea",
                required: true,
                hint: "Record the observed condition. If none, use the wording confirmed by Shuttle Air.",
            },
            {
                key: "action_taken",
                label: "Action taken",
                type: "textarea",
                required: false,
                hint: "Record work already performed. This does not authorize release to service.",
            },
        ],
    },
    {
        id: "totals",
        title: "Accumulated times",
        fields: [
            {
                key: "airframe_brought_forward",
                label: "Airframe: Total brought forward",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "airframe_this_flight",
                label: "Airframe: Total this flight",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "airframe_total_to_date",
                label: "Airframe: Total to date",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "airframe_due_100_hrs",
                label: "Airframe: Due 100 hrs",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "left_engine_brought_forward",
                label: "Left engine: Total brought forward",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "left_engine_this_flight",
                label: "Left engine: Total this flight",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "left_engine_total_to_date",
                label: "Left engine: Total to date",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "left_engine_due_100_hrs",
                label: "Left engine: Due 100 hrs",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "right_engine_brought_forward",
                label: "Right engine: Total brought forward",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "right_engine_this_flight",
                label: "Right engine: Total this flight",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "right_engine_total_to_date",
                label: "Right engine: Total to date",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "right_engine_due_100_hrs",
                label: "Right engine: Due 100 hrs",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "left_propeller_brought_forward",
                label: "Left propeller: Total brought forward",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "left_propeller_this_flight",
                label: "Left propeller: Total this flight",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "left_propeller_total_to_date",
                label: "Left propeller: Total to date",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "left_propeller_due_100_hrs",
                label: "Left propeller: Due 100 hrs",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "right_propeller_brought_forward",
                label: "Right propeller: Total brought forward",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "right_propeller_this_flight",
                label: "Right propeller: Total this flight",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "right_propeller_total_to_date",
                label: "Right propeller: Total to date",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
            {
                key: "right_propeller_due_100_hrs",
                label: "Right propeller: Due 100 hrs",
                type: "number",
                required: false,
                hint: "Copy the recorded value; applicability and units await confirmation.",
            },
        ],
    },
    {
        id: "fluids",
        title: "Oil and fuel",
        fields: [
            {
                key: "oil_left_engine_arrival",
                label: "Oil, left engine: Arrival",
                type: "number",
                required: false,
                hint: "Oil: quarts. Fuel: US gallons.",
            },
            {
                key: "oil_left_engine_departure",
                label: "Oil, left engine: Departure",
                type: "number",
                required: false,
                hint: "Oil: quarts. Fuel: US gallons.",
            },
            {
                key: "oil_right_engine_arrival",
                label: "Oil, right engine: Arrival",
                type: "number",
                required: false,
                hint: "Oil: quarts. Fuel: US gallons.",
            },
            {
                key: "oil_right_engine_departure",
                label: "Oil, right engine: Departure",
                type: "number",
                required: false,
                hint: "Oil: quarts. Fuel: US gallons.",
            },
            {
                key: "fuel_left_aux_arrival",
                label: "Fuel, left auxiliary: Arrival",
                type: "number",
                required: false,
                hint: "Oil: quarts. Fuel: US gallons.",
            },
            {
                key: "fuel_left_aux_departure",
                label: "Fuel, left auxiliary: Departure",
                type: "number",
                required: false,
                hint: "Oil: quarts. Fuel: US gallons.",
            },
            {
                key: "fuel_left_main_arrival",
                label: "Fuel, left main: Arrival",
                type: "number",
                required: false,
                hint: "Oil: quarts. Fuel: US gallons.",
            },
            {
                key: "fuel_left_main_departure",
                label: "Fuel, left main: Departure",
                type: "number",
                required: false,
                hint: "Oil: quarts. Fuel: US gallons.",
            },
            {
                key: "fuel_right_main_arrival",
                label: "Fuel, right main: Arrival",
                type: "number",
                required: false,
                hint: "Oil: quarts. Fuel: US gallons.",
            },
            {
                key: "fuel_right_main_departure",
                label: "Fuel, right main: Departure",
                type: "number",
                required: false,
                hint: "Oil: quarts. Fuel: US gallons.",
            },
            {
                key: "fuel_right_aux_arrival",
                label: "Fuel, right auxiliary: Arrival",
                type: "number",
                required: false,
                hint: "Oil: quarts. Fuel: US gallons.",
            },
            {
                key: "fuel_right_aux_departure",
                label: "Fuel, right auxiliary: Departure",
                type: "number",
                required: false,
                hint: "Oil: quarts. Fuel: US gallons.",
            },
            {
                key: "oil_total_before_uplift",
                label: "Oil total before uplift (quarts)",
                type: "number",
                required: false,
                hint: "Recorded value only; totals are not calculated.",
            },
            {
                key: "oil_total_uplift",
                label: "Oil total uplift (quarts)",
                type: "number",
                required: false,
                hint: "Recorded value only; totals are not calculated.",
            },
            {
                key: "fuel_total_before_refuel",
                label: "Fuel total before refuel (US gallons)",
                type: "number",
                required: false,
                hint: "Recorded value only; totals are not calculated.",
            },
            {
                key: "fuel_total_uplift",
                label: "Fuel total uplift (US gallons)",
                type: "number",
                required: false,
                hint: "Recorded value only; totals are not calculated.",
            },
        ],
    },
    {
        id: "inspection",
        title: "Pre-flight inspection reference",
        fields: [
            {
                key: "inspection_name",
                label: "Inspector name",
                type: "text",
                required: false,
                hint: "",
            },
            {
                key: "inspection_licence",
                label: "A&P licence number",
                type: "text",
                required: false,
                hint: "",
            },
            {
                key: "inspection_utc_date",
                label: "Inspection UTC date",
                type: "date",
                required: false,
                hint: "Reference information only. No signature or certification is recorded.",
            },
        ],
    },
];

export const logbook_fields = logbook_sections.flatMap(
    (section) => section.fields,
);
export function empty_logbook_values(): LogbookFormValues {
    return Object.fromEntries(
        logbook_fields.map((field) => [field.key, ""]),
    ) as LogbookFormValues;
}
export const logbook_preview_note =
    "Technical-logbook preview · Scope, fields, time notation, and component units await client confirmation. One entry represents one flight row. No digital signatures or release-to-service approval. Changes reset on refresh.";
